language: node_js
node_js:
- "10"

cache:
  directories:
  - "node_modules"

branches:
  only:
  - tnt2019

install:
- npm install
- npm run generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_NEW_TOKEN
  target-branch: master
  local-dir: dist
  on:
    branch: tnt2019

#deploy:
#  provider: firebase
#  project: "touraine-tech"
#  skip_cleanup: true
#  on:
#    branch: dev
#  token:
#    secure: $FIREBASE_TOKEN

notifications:
  slack:
    rooms:
      secure: $SLACK_TOKEN
    template:
    - $TRAVIS_COMMIT_MESSAGE
    - $TRAVIS_PULL_REQUEST_SLUG
    - 'Deployed at'
    - $DEPLOYED_TO
