language: node_js
node_js:
- "10"

cache: npm

branches:
  only:
  - develop

install:
- npm ci
- npm run generate

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_NEW_TOKEN
#  target-branch: master
#  local-dir: dist
#  on:
#    branch: develop

deploy:
  provider: firebase
  edge: true
  project: "touraine-tech"
  skip_cleanup: true
  on:
    branch: develop
  token:
    secure: $FIREBASE_TOKEN

notifications:
  slack:
    rooms:
    - secure: $SLACK_TOKEN
    template:
    - $TRAVIS_COMMIT_MESSAGE
    - $TRAVIS_PULL_REQUEST_SLUG
    - 'Deployed at'
    - $DEPLOYED_TO
